### ISSUE TITLE
Organise readMe file

### ISSUE THREAD

**Issue by chantalcassinijones** [sonia-robin/dish-discovery-app#17]
Read me File 

- [x] links to all resources and documentation used 
- [x] section on how to use our application 
- [x] section with screenshots 
- [x] describe application
- [x] mention all collaborators

**Comment by Setsu-Adachi** [comment]
The Darf of README is ready to review—resources, documentation and how to use it need to be added when it's done.

**Comment by Setsu-Adachi** [comment]
As the main folder is locked, I cannot commit readme on the folder. Meanwhile, I have added it in my css styling reppo. Please move it once it's been reviewed.

**Comment by Setsu-Adachi** [comment]
all done, please refer  58-read-me-file-take-screenshot-and-add-any-links-and-usage-section-setsu

**Comment by chantalcassinijones** [comment]
done
